### PR TITLE
correctly assign expressions where brackets are used & the middle val is undefined

### PR DESCRIPTION
**Pull request by fdintino**
This incorporates the changes in angular.js from angular/angular.js@c03ad24

### CODE REVIEW

**Comment by fdintino** [comment]
formerly pull request #4, but switched the branch so I could use master for other purposes

**Comment by jhnns** [comment]
Thank you! Is the `assign()` method the recommended way to assign variables? Does the old way still work?

**Comment by fdintino** [comment]
If by the old way you mean `compile('a.b.c = "foo"')(scope)` then it still works, that just calls `assign()` under the hood.

**Comment by jhnns** [comment]
Shipped with `v0.3.0`. Thx!

**Pull request merged**
